project:
  type: book
  output-dir: _book

book:
  title: UDD networks 2024
  chapters: 
    - index.qmd
    - part: Day 1
      chapters:
        - 01-overview/index.qmd
        - 02-random-graphs/index.qmd
        - 03-behavior-and-coevolution/index.qmd
        - 04-lab-1/index.qmd
        - 05-intro-to-ergms/index.qmd
    - part: Day 2
      chapters:
        - 06-ergms-cont/index.qmd
        - 07-odd-balls/index.qmd
        - 08-lab-2/index.qmd
        - 09-advanced-ergms/index.qmd
        - 10-new-topics/index.qmd
    - references.qmd
  downloads:
  - epub
  - pdf


bibliography: references.bib

format:
  html:
    html-math-method: katex
    toc: true
    number-sections: true
    embed-resources: true
