project:
  type: website
  output-dir: docs
  render: 
    - "*/index.qmd"
    - "index.qmd"

website:
  title: UDD networks 2024
  
  navbar: 
    right:
      - text: Fundamentals
        href: 00-fundamentals/index.qmd
    left:
      - text: Home
        href: index.qmd
      - text: Day I
        menu: 
          - text: Overview
            href: 01-overview/index.qmd
          - text: Random graphs
            href: 02-random-graphs/index.qmd
          - text: Behavior and coevolution
            href: 03-behavior-and-coevolution/index.qmd
          - text: Intro to ERGMs
            href: 04-intro-to-ergms/index.qmd
      - text: Day II
        menu:
          - text: ERGMs (cont.)
          - text: Odd balls
          - text: ERGM advances

format:
  html:
    html-math-method: katex
    bibliography: ../references.bib
    toc: true
    number-sections: true
    embed-resources: true
