project:
  type: book
  output-dir: docs

execute: 
  cache: true

book:
  title: UDD networks 2024
  author: George G. Vega Yon, Ph.D.
  date: 2024-01-14

  chapters: 
    - index.qmd
    - part: Day 1
      chapters:
        - 01-overview.qmd
        - 02-random-graphs.qmd
        - 03-behavior-and-coevolution.qmd
        - 04-lab-1.qmd
        - 05-intro-to-ergms.qmd
    - part: Day 2
      chapters:
        - 06-ergms-cont.qmd
        - 07-odd-balls.qmd
        - 08-lab-2.qmd
        - 09-advanced-ergms.qmd
        - 10-new-topics.qmd
    - references.qmd
  downloads:
  - epub
  - pdf


bibliography: references.bib

format:
  html:
    html-math-method: katex
    toc: true
    number-sections: true
  pdf:
    include-in-header: 
      - text: |
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{bm}
  epub: default

