---
format: gfm
bibliography: ../references.bib
number-sections: true
---

# Fundamentals

- When networks are involved, statistical inference becomes tricky.

- The IID assumption is violated by construction.

- Although it is tempting to use the same tools as in the IID case, they are
  not valid.

# Types of problems

Overall, we can classify the problems according to two dimensions:

- **Behavior** Is the individual level behavior random or deterministic?

- **Network** Is the network random or deterministic?

Of the following cases, which ones can be treated with "regular statistical methods"?

> a. Egocentric study 1: Analyze how the network structure affects health outcomes.
>
> b. Egocentric study 2: Investigate what network structures are more prevalent in a population sample.
>
> c. Egocentric study 3: Elucidate whether the prevalence of a given network structure is higher in one population than in another.
>
> d. Country-level networks: Analyze whether neighboring countries tend to adopt international treaties at the same time.
>
> e. Phylogenomics: Study a given phenotype in a population of organisms related by a phylogenetic tree. 

# Available methods

## When the network is deterministic

### Single network

If the network is fixed (or treated as if it were fixed,) it is most likely that a traditional statistical analysis can be performed. For instance, if we are interested in influence behavior between adolescents, and we assume influence is a process that takes time, then a lagged regression may suffice [@hayeSmokingDiffusionNetworks2019; @valenteDiffusionContagionProcesses2020; @valenteNetworkInfluencesPolicy2019].

$$
\mathbf{y}_t = \rho \mathbf{W} \mathbf{y}_{t-1} + \mathbf{X} \bm{\beta} + \bm{\varepsilon}, \quad \varepsilon_i \sim \mbox{N}\left(0, \sigma^2\right)
$$ {#eq-lagged-regression}

where $\mathbf{y}_t$ is a vector of behaviors at time $t$, $\mathbf{W}$ is the row-stochastic adjacency matrix of the network, $\mathbf{X}$ is a matrix of covariates, and the elements of $\bm{\varepsilon}\equiv \{\varepsilon_i\}$ distribute normal with mean zero and variance $\sigma^2$.

Nonetheless, if assuming a lagged influence effect is no longer possible, then the regular regression model is no longer valid. Instead, we can resort to a Spatial Autocorrelation Regression Model [SAR] [see @lesageIntroductionSpatialEconometrics2008]:

$$
\mathbf{y} = \rho \mathbf{W} \mathbf{y} + \mathbf{X} \bm{\beta} + \bm{\varepsilon},\quad \bm{\varepsilon} \sim \mbox{MVN}\left(0, \Sigma^2\right)
$$ {#eq-sar}

furthermore

$$
\mathbf{y} = \left(I - \rho\mathbf{W}\right)^{-1}\left(\mathbf{X}\bm{\beta} + \bm{\varepsilon}\right)
$$

Where $\bm{\varepsilon}$ now distributes Multivariate Normal with mean zero and covariance matrix $\Sigma^2 \mathbf{I}$.

::: {.callout-tip}
What is the appropriate network to use in the SAR model? According to @lesageBiggestMythSpatial2014, it is not very important. Since $(I_n - \rho \mathbf{W})^{-1} = \rho \mathbf{W} + \rho^2 \mathbf{W}^2 + \dots$.
:::

### Multiple networks

Sometimes, instead of a single network, we are interested in understanding how network-level properties affect the behavior of individuals. For instance, we may be interested in understanding the relation between triadic closure and income within a sample of independent egocentric networks; in such a case, as the networks are independent, a simple regression analysis may suffice.

## When the network is random

### Deterministic behavior

In this case, the behavior is treated as given, *i.e.*, a covariate/feature of the model. When such is the case, the method of choice is the Exponential Random Graph Model [ERGM] [@lusherExponentialRandomGraph2013; @krivitskyExponentialfamilyRandomGraph2012 and others].

### Random behavior

## Non-parametric approaches

Other common scenarios involve more convoluted/complex questions. For instance, in the case of dyadic behavior @bellSensingEatingMimicry2019.

In @tanakaImaginaryNetworkMotifs2024, we study the prevalence of perception-based network motifs. While the ERGM framework would be a natural choice, as a first approach, we used non-parametric tests for hypothesis testing.



# References